package hotels;

import java.util.concurrent.atomic.AtomicLong;
import org.springframework.web.bind.annotation.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;

@RestController
public class HotelController {
    private static final String template = "Hello, %s!";
    private final AtomicLong counter = new AtomicLong();


    @Autowired // This means to get the bean called PersonelRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private PersonelRepository personelRepository;

    @PostMapping(path="/personel") // Map ONLY POST Requests
    public @ResponseBody String addNewUser (@RequestParam String name
            , @RequestParam String surname
            , @RequestParam String email
            , @RequestParam Integer phoneNumber) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Personel p = new Personel();
        p.setName(name);
        p.setSurname(surname);
        p.setEmail(email);
        p.setPhoneNumber(phoneNumber);
        personelRepository.save(p);
        return "Saved";
    }

    @GetMapping(path="/personel/all")
    public @ResponseBody Iterable<Personel> getAllUsers() {
        // This returns a JSON or XML with the users
        return personelRepository.findAll();
    }


}